
# Use kramdown so that Mathjax can render
markdown: kramdown
kramdown:
  input: GFM

# Syntax highlighting
highlighter: rouge

# Site Settings
title: Jonty Sinai
description: >- # this means to ignore newlines until "baseurl:"
  Mathematician. Yogi. Runner. Dreamer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jontysinai.github.io" 

# Author
name: 'Jonty Sinai'
author: 'Jonty Sinai'
linkedin_username: jontysinai
github_username:  jontysinai
twitter_username: jontysinai_

# Build settings
theme: jekyll-theme-clean-blog
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-paginate

# posts index
paginate: 5
paginate_path: "/posts/page:num/"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
