# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Use kramdown so that Mathjax can render
markdown: kramdown
kramdown:
  input: GFM

# syntax highlightinh
highlighter: rouge

# Site settings
title: "Jonty Sinai"
description: > # this means to ignore newlines until "email:"
  Mathematician. Yogi. Runner. Dreamer

email: jontysinai@gmail.com
#blog log
logo: "/assets/images/jonty-icon.png"
float_logo: true # true, false (default)

# blog cover
cover: "https://source.unsplash.com/9r4kV5VrdSQ/1600x900"

name: 'Jonty Sinai'
author: 'Jonty Sinai'
author_image: "/assets/images/jonty-icon.png"

paginate:	5

url: "https://jontysinai.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@jontysinai_'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	github
    url:	https://github.com/jontysinai
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:
    
  - icon:	twitter
    url:	https://twitter.com/jontysinai_
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	linkedin
    url:	https://www.linkedin.com/in/jontysinai/
    desc: Connect with me on LinkedIn
    share_url: 
    share_title:
    share_link:
